# Generated by Django 5.0.7 on 2024-08-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpuser",
            name="key",
            field=models.BinaryField(
                default=b"1576304f2e379878928145565ac99fadf4b68a2d11457f984e53f929f480073e57cfd341ff79cb96c222c373b6f824aa471bfc9b6736d420bdf489640bc36516",
                max_length=80,
            ),
        ),
    ]
