# Generated by Django 5.0.7 on 2024-08-05 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0002_alter_otpuser_key"),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpuser",
            name="key",
            field=models.CharField(
                default="0d944250ee18c911f8f6661fe77b14fff46cbf16c36f008a4a128030b389513f9b4b1b1ae9ae9ae5b804d3b868626227fe9113542a28a99b5aac6d7dc56be802",
                max_length=80,
            ),
        ),
    ]
