# Generated by Django 5.0.7 on 2024-08-05 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0003_alter_otpuser_key"),
    ]

    operations = [
        migrations.AddField(
            model_name="otpuser",
            name="first_seen",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="otpuser",
            name="key",
            field=models.CharField(
                default="5193cd06cc9cef6d3951d05f225126ed68298fc434ab3ec82f792540d5bc175302fc7b790a93290dfd30a78640ce2f5e7cf46ff82a4712900eb7ebd7baaf86e7",
                max_length=80,
            ),
        ),
    ]
