# Generated by Django 5.0.7 on 2024-08-08 20:14

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Auth", "0005_otpuser_last_get_request_time_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="otpresendrefrence",
            name="token",
            field=models.CharField(
                default="bbc1ef2c-aade-47ed-83fd-8432467fd816", max_length=80
            ),
        ),
        migrations.AlterField(
            model_name="otpuser",
            name="key",
            field=models.CharField(
                default="e1151dce23362aa1d38d98617da8919d20d4ef8556aed861bf69dd6affff8b3e6d5a968722b817246ef3182eac4d5544b619eafc8fcafcc694c858ae4b6e0c49",
                max_length=80,
            ),
        ),
        migrations.CreateModel(
            name="SiginRequestCount",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("count", models.PositiveIntegerField(default=0)),
                (
                    "last_request_time",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
